os: osx
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode7.3
language: ruby
rvm:
  - 2.2.4
